#**개념 정리**

### Numpy (넘파이)
: 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지.

많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 이들 알고리즘의 입력 데이터와 출력 데이터를 넘파이 배열 타입으로 사용함.

넘파이가 배열을 다루는 기본 방식을 이해하는 것이 다른 데이터 핸들링 패키지 이해에도 많은 도움이 됨.

### 넘파이 ndarray 개요

In [ ]:
import numpy as np # 넘파이 모듈 임포트

- ndarray : 넘파이의 기반 데이터 타입. 다차원 배열을 쉽게 생성/연산 수행
- array()함수 : 파이썬의 리스트와 같은 다양한 인자를 입력받아 ndarray로 변환하는 기능 수행. 인자로는 파이썬의 리스트 객체가 주로 사용됨.
- ndarray배열의 shape변수 : ndarray의 크기(행과 열의 수->튜플 형태)를 갖고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음

In [ ]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape) # 결과 = 1차원 array로 3개의 데이터를 갖고 있음

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape) # 결과 = 2차원 array로 2*3개(로우2,칼럼3)의 데이터를 갖고 있음

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape) # 결과 = 로우1, 칼럼3으로 구성된 2차원 데이터

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim)) # ndarray.ndim으로 array의 차원 확인

array1: 1차원, array2: 2차원, array3: 2차원


### ndarray의 데이터 타입

- ndarray내의 데이터 값: 숫자(int,unsigned int,float,complex), 문자열, 불 모두 가능
- ndarray내의 데이터 타입: 연산 특성상 같은 데이터 타입만 가능 (dtype 속성을 확인하기)

만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면, 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용함.
- ndarray내 데이터값의 타입 변경: astype()에 인자로 원하는 타입을 문자열로 지정 (메모리를 더 절약해야 할 때 주로 이용됨)

In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype) # 숫자형 값인 1,2가 모두 문자열 값인 '1','2'로 변환됨

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # int1,2가 모두 float64형으로 변환됨

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') # ndarray 내 데이터값의 타입 변경
print(array_float,array_float.dtype)

[1. 2. 3.] float64


### ndarray를 편리하게 생성하기 - arange, zeros, ones

특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우

주로 테스트용으로 데이터를 만들거나 대규모 데이터를 일괄 초기화해야 할 경우

- arragne() : 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환

defalut 함수 인자 값은 stop값/start값도 부여하여 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수도 있음.

In [ ]:
sequence_array = np.arange(10) # 0부터 stop값인 10에서 -1을 더한 9까지의 연속 숫자값으로 구성된 1차원 ndarray를 만들어줌
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


- zero() : 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
- ones() : 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarry로 반환

(함수 인자로 dtype을 정해주지 않으면 defalut로 float64형의 데이터로 ndarray를 채움)

In [ ]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

- reshape() 메서드 : ndarray를 특정 차원 및 크기로 변환. 변환을 원하는 크기를 함수 인자로 부여

지정된 사이즈로 변경이 불가능하면 오류 발생

In [ ]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4,3) # (4,3) 사이즈로 변경 불가능하기 때문에 오류가 나올 수 밖에 없음

ValueError: cannot reshape array of size 10 into shape (4,3)

- reshape() 인자로 -1을 적용 : reshape()을 더 효율적으로 사용하는 것. -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해줌

In [ ]:
array1 = np.arange(10) # 0~9까지의 데이터
print(array1)
array2 = array1.reshape(-1,5) # 로우 인자가 -1,칼럼 인자가 5 / array1과 호환될 수 있는 2차원 ndarray로 변환하되 고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환하라는 의미
                              # 즉 10개의 1차원 데이터와 호환될 수 있는 고정된 5개 칼럼에 맞는 로우 개수는 2이므로 2x5의 2차원 ndarray로 변환하는 것
print('array2 shape:',array2.shape)
array3 = array1.reshape(5,-1) # 10개의 1차원 데이터와 호환될 수 있는 고정된 5개의 로우에 맞는 칼럼은 2이므로 5x2의 2차원 ndarray로 변환
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) # 10개의 1차원 데이터를 고정된 4개의 칼럼을 가진 로우로 변경 불가능하므로 에러 발생

ValueError: cannot reshape array of size 10 into shape (4)

- -1 인자는 reshape(-1,1)와 같은 형태로 자주 사용됨
- reshape(-1,1) : 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장함
- 여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용됨
- tolist() 매서드 : ndarray를 리스트 자료형으로 변환

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:/n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:/n [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


슬라이싱

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


팬시 인덱싱

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>',array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


불린 인덱싱

In [ ]:
array1d = np.arange(start=1, stop=10)
# []안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :',array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()

행렬 정렬

- 오름차순 : np.sort(), ndarray, sort()의 디폴트 정렬값
- 내림차순 : [::-1]

In [ ]:
org_array = np.array([3,1,9,5])
print('원본 행렬:',org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


정렬된 행렬의 인덱스를 반환하기

In [ ]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
import numpy as np

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

행렬 내적 (행렬 곱)

In [ ]:
A = np.array( [[1,2,3],
               [4,5,6]])
B = np.array( [[7,8],
               [9,10],
               [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


전치 행렬

In [ ]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
